spring:
  application:
    name: apollo-adminservice
  profiles:
    active: dev
ctrip:
  appid: 100003172
server:
  port: 8090
management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
logging:
  file: /home/worker/logs/apollo-adminservice/apollo-adminservice.log