spring:
  application:
    name: apollo-configservice
  profiles:
    active: dev
ctrip:
  appid: 100003171
server:
  port: 8080
management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    web:
      server:
        auto-time-requests: true
logging:
  file: /home/worker/logs/apollo-configservice/apollo-configservice.log
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    status-page-url-path: /info
    health-check-url-path: /health
  server:
    peerEurekaNodesUpdateIntervalMs: 60000
    enableSelfPreservation: false
  client:
    serviceUrl:
      defaultZone: http://${spring.cloud.client.ip-address}:8080/eureka/
    eurekaServiceUrlPollIntervalSeconds: 60