spring:
  application:
    name: apollo-portal
  profiles:
    active: auth
  datasource:
    username: root
    password: ZHBroot!!2018
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://zhb.lovegq.cn:3366/ApolloPortalDB?useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: select 1
      minimum-idle: 10
      maximum-pool-size: 150
      idle-timeout: 600000
      max-lifetime: 1800000
      read-only: false
      auto-commit: true
      validation-timeout: 5000
  jpa:
    properties:
      hibernate:
        query:
          plan_cache_max_size: 192
management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP
server:
  port: 8070
  compression:
    enabled: true
  tomcat:
    use-relative-redirects: true
logging:
  file: /home/worker/logs/apollo-portal/apollo-portal.log